SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBCLASSIFICACAO;
CREATE DATABASE DBCLASSIFICACAO;
USE DBCLASSIFICACAO;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(45)
	, IDADE INT
);

CREATE TABLE CLASSIFICACAO (	
	CRIANCAS INT
	, JOVENS INT
	, ADULTOS INT
);

DELIMITER $$

CREATE TRIGGER TR_ALUNO_AI AFTER INSERT ON ALUNO FOR EACH ROW
BEGIN

	IF (NEW.IDADE < 10) THEN
		UPDATE CLASSIFICACAO SET CRIANCAS = CRIANCAS + 1;
	ELSEIF (NEW.IDADE >= 10) AND (NEW.IDADE <= 18) THEN 
		UPDATE CLASSIFICACAO SET JOVENS = JOVENS + 1;
	ELSE
		UPDATE CLASSIFICACAO SET ADULTOS = ADULTOS + 1;
    END IF;

END $$

CREATE TRIGGER TR_ALUNO_AD AFTER DELETE ON ALUNO FOR EACH ROW
BEGIN

	IF (OLD.IDADE < 10) THEN
		UPDATE CLASSIFICACAO SET CRIANCAS = CRIANCAS - 1;
	ELSEIF (OLD.IDADE >= 10) AND (OLD.IDADE <= 18) THEN 
		UPDATE CLASSIFICACAO SET JOVENS = JOVENS - 1;
	ELSE
		UPDATE CLASSIFICACAO SET ADULTOS = ADULTOS - 1;
    END IF;

END $$

CREATE TRIGGER TR_ALUNO_AU AFTER UPDATE ON ALUNO FOR EACH ROW
BEGIN

	IF (OLD.IDADE < 10) THEN
		UPDATE CLASSIFICACAO SET CRIANCAS = CRIANCAS - 1;
	ELSEIF (OLD.IDADE >= 10) AND (OLD.IDADE <= 18) THEN 
		UPDATE CLASSIFICACAO SET JOVENS = JOVENS - 1;
	ELSE
		UPDATE CLASSIFICACAO SET ADULTOS = ADULTOS - 1;
    END IF;
    
    IF (NEW.IDADE < 10) THEN
		UPDATE CLASSIFICACAO SET CRIANCAS = CRIANCAS + 1;
	ELSEIF (NEW.IDADE >= 10) AND (NEW.IDADE <= 18) THEN 
		UPDATE CLASSIFICACAO SET JOVENS = JOVENS + 1;
	ELSE
		UPDATE CLASSIFICACAO SET ADULTOS = ADULTOS + 1;
    END IF;

END $$

DELIMITER ;




INSERT INTO CLASSIFICACAO VALUES (0,0,0);

/*
Regra:
abaixo 10 - Criancas
10 a 18 - Jovens
Acima de 18 - Adulto
*/


SELECT * FROM ALUNO;
SELECT * FROM CLASSIFICACAO;

INSERT INTO ALUNO (NOME, IDADE)VALUES('ANDRE', 9);
UPDATE ALUNO SET IDADE = 16;
DELETE FROM ALUNO;
